### ISSUE TITLE
P2318 A Provenance-aware Memory Object Model for C

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#12]
Issue tracking the SG22 discussion of [P2318R0](https://wg21.link/p2318r0) A Provenance-aware Memory Object Model for C (Jens Gustedt, Peter Sewell, Kayvan Memarian, Victor B. F. Gomes, Martin Uecker)

[wg21 issue](https://github.com/cplusplus/papers/issues/1011)

**Comment by ThePhD** [comment]
This is an advisory paper that does not actually propose anything for WG21 to do with; WG21 should read the proposal and if they like the underlying model being developed express interest so it can be taken forward into WG21 as well. Until that time, there's nothing for us to do here.

**Comment by NinaRanns** [comment]
See [P2434 Nondeterministic pointer provenance #35](https://github.com/sg22-c-cpp-standard-compatibility/sg-compatibility/issues/35) for minutes of discussion.
