### ISSUE TITLE
P2309 A common C/C++ core specification

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#13]
Issue tracking the SG22 discussion of [P2309R0](https://wg21.link/p2309r0) A common C/C++ core specification (Jens Gustedt)

[wg21 issue](https://github.com/cplusplus/papers/issues/994)

**Comment by ThePhD** [comment]
This paper will likely not see an update until there is agreement between WG21 and WG14 that the languages should developer a core specification between the languages. Initial WG21 reception (among its member, no official stated position) was "we hate this"; I doubt this proposal will see progress but if the author publishes another revision we should take it into consideration.
