### ISSUE TITLE
P2307 Lvalue closures

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#14]
Issue tracking the SG22 discussion of [P2307R0](https://wg21.link/p2307r0) Lvalue closures (Jens Gustedt)

[wg21 issue](https://github.com/cplusplus/papers/issues/993)

**Comment by ThePhD** [comment]
Similar to #15, #16, and #17 -- no risk of compatibility breakage here.
