### ISSUE TITLE
P2306 Type-generic lambdas

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#15]
Issue tracking the SG22 discussion of [P2306R0](https://wg21.link/p2306r0) Type-generic lambdas (Jens Gustedt)

[wg21 issue](https://github.com/cplusplus/papers/issues/992)

**Comment by ThePhD** [comment]
Similar to #16 and #17  -- nothing we need to do here, no intent to break C++ compatibility from these proposals.
