### ISSUE TITLE
P2303 Function literals and value closures

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#17]
Issue tracking the SG22 discussion of [P2303R0](https://wg21.link/p2303r0) Function literals and value closures (Jens Gustedt)

[WG21 issue](https://github.com/cplusplus/papers/issues/989)

**Comment by ThePhD** [comment]
We don't have to discuss the Lambda proposals because Jens's designs are not deviating from how WG21 wants their lambdas to work in any appreciable or detectable manner. There's no compatibility risk here.
