### ISSUE TITLE
P2039 do_until Loop

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#21]
Issue tracking the SG22 discussion of [P2039R0](https://wg21.link/p2039r0) do_until Loop (Menashe Rosemberg)

[WG21 issue](https://github.com/cplusplus/papers/issues/769)

**Comment by ThePhD** [comment]
We don't need to discuss this, per se: while WG14 can accept this, WG21 is free to invent language syntax separately from WG14 without needing SG22 or WG14 approval.
