### ISSUE TITLE
P1315 secure_clear / memset_explicit

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#23]
Issue tracking the SG22 discussion of [P1315R1](https://wg21.link/p1315r1) secure_val: a secure-clear-on-move type (Miguel Ojeda)

[WG21 issue](https://github.com/cplusplus/papers/issues/67)

**Comment by ThePhD** [comment]
We do not need to review this in our group, the C version was already accepted. All WG21 has to do is catch up.

https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2897.htm
