### ISSUE TITLE
P2884 R0 assert Should Be A Keyword In C++26

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#5]
Issue tracking the SG22 discussion of WG21 paper [P2884R0](https://wg21.link/p2884r0) assert Should Be A Keyword In C++26 (Alisdair Meredith)

[WG21 issue](https://github.com/cplusplus/papers/issues/1561)

**Comment by ThePhD** [comment]
Should discuss so WG14 members can weigh in.

**Comment by ThePhD** [comment]
Spoke to the author; will be sending a revision and they are intent that the paper will be closed until a later date. The issue can be reopened when such a change is made.
