### ISSUE TITLE
P2865 R2 Remove Deprecated Array Comparisons from C++26

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#7]
Issue tracking the SG22 discussion of WG21 paper [P2865R0](https://wg21.link/p2865r0) Remove Deprecated Array Comparisons from C++26 (Alisdair Meredith)

[WG21 issue](https://github.com/cplusplus/papers/issues/1555)

**Comment by ThePhD** [comment]
We should schedule this paper and let Alisdair make the case to the compatibility group and get a feeling for how they feel about it.

**Comment by NinaRanns** [comment]
Seen in EWG in Kona meeting. 
Consensus to ask WG14 for compatibility opinion before forwarding to CWG for inclusion in C++26. See WG21 issue for more details.

**Comment by NinaRanns** [comment]
Discussed in a telco on the 16/7/2024. See [minutes](https://github.com/sg22-c-cpp-standard-compatibility/sg-compatibility#July-26th-2024)
No compatibility concerns raised.

**Comment by NinaRanns** [comment]
Discussed in a telco on the 16/7/2024. See [minutes](https://github.com/sg22-c-cpp-standard-compatibility/sg-compatibility#July-26th-2024)
No compatibility concerns raised.
