### ISSUE TITLE
P2735 C xor C++ Programming

### ISSUE THREAD

**Issue by NinaRanns** [sg22-c-cpp-standard-compatibility/sg-compatibility#9]
Issue tracking the SG22 discussion of WG21 paper [P2735R0](https://wg21.link/p2735r0) C xor C++ Programming (Aaron Ballman)

[WG21 Issue](https://github.com/cplusplus/papers/issues/1428)

**Comment by ThePhD** [comment]
This is an advisory paper that discusses differences. It can be used as the basis for other proposals or help other clean up efforts (e.g., Alisdair's papers on C and C++ differences and the Annex in the C++ standard that has not been updated in probably a decade now).

But we don't need to see this paper explicitly.
